# Pytorch Tutorials

> https://tutorials.pytorch.kr/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-pyz 

In [2]:
from __future__ import print_function
import torch

초기화되지 않은 5x3 행렬

In [4]:
x = torch.empty(5, 3)
print(x)

tensor([[1.9721e+13, 4.5879e-41, 1.9721e+13],
        [4.5879e-41, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [6.2121e+22, 1.8788e+31, 1.7220e+22],
        [9.4429e-09, 5.2477e-08, 1.2915e-11]])


무작위로 초기화된 5x3 행렬

In [5]:
x = torch.rand(5, 3)
print(x)

tensor([[0.9273, 0.0560, 0.6582],
        [0.4907, 0.4073, 0.8053],
        [0.4339, 0.2840, 0.1525],
        [0.5254, 0.7438, 0.6784],
        [0.6218, 0.8201, 0.8182]])


dype이 long이고 0으로 채워진 5x3 행

In [13]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


데이터로부터 tensor를 직접 생성

In [14]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


존재하는 tensor를 바탕으로 tensor 생성

사용자로부터 제공된 새로운 값이 없는 한, 입력 tensor의 속성들(예. dtype)을 재사용함

In [15]:
x = x.new_ones(5, 3, dtype=torch.double)  # new_* 메소드는 크기를 받음
print(x)

x = torch.randn_like(x, dtype=torch.float)  # dtype을 오버라이드(Override) 함
print(x)  # 결과는 동일한 크기를 갖음

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.5645,  2.7258,  0.6389],
        [ 2.5049, -0.6945, -0.7006],
        [-0.2111, -0.9514,  0.0967],
        [-0.6107, -1.1964, -1.4469],
        [-1.9624,  0.7164,  1.5177]])


행렬의 크기 (튜플(tuple)로 반환)

In [16]:
print(x.size())

torch.Size([5, 3])


## 연산(Operation)

덧셈: 문법1

In [22]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.1289,  3.4075,  1.1927],
        [ 3.0947, -0.2948,  0.0490],
        [ 0.4872, -0.1578,  0.2912],
        [ 0.3358, -0.3909, -1.0933],
        [-1.0289,  0.7512,  1.9151]])


덧셈: 문법2

In [24]:
print(torch.add(x, y))

tensor([[-0.1289,  3.4075,  1.1927],
        [ 3.0947, -0.2948,  0.0490],
        [ 0.4872, -0.1578,  0.2912],
        [ 0.3358, -0.3909, -1.0933],
        [-1.0289,  0.7512,  1.9151]])


덧셈: 결과 tensor를 인자로 제공

In [25]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.1289,  3.4075,  1.1927],
        [ 3.0947, -0.2948,  0.0490],
        [ 0.4872, -0.1578,  0.2912],
        [ 0.3358, -0.3909, -1.0933],
        [-1.0289,  0.7512,  1.9151]])


덧셈: 바꿔치기(In-place) 방식

In [26]:
# y에 x 더하기
y.add_(x)
print(y)

tensor([[-0.1289,  3.4075,  1.1927],
        [ 3.0947, -0.2948,  0.0490],
        [ 0.4872, -0.1578,  0.2912],
        [ 0.3358, -0.3909, -1.0933],
        [-1.0289,  0.7512,  1.9151]])


바꿔치기(In-place) 방식으로 tensor의 값을 변경하는 연산은 `_`를 접미사로 갖음.

ex) `x.copy_(y)`, `x.t_()` 는 `x`를 변경

NumPy식 인덱싱 표기

In [27]:
print(x[:, 1])

tensor([ 2.7258, -0.6945, -0.9514, -1.1964,  0.7164])


크기 변경: tensor의 크기(size)나 모양(shape)을 변경하고 싶다면 `torch.view`를 사용

In [28]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # -1은 다른 차원들을 사용하여 유추
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


tensor에 하나의 값만 존재하는 경우 `.item()`을 사용하면 숫자 값을 얻음

In [29]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.3610])
0.3610249161720276


## NumPy 변환(Bridge)

Torch Tensor를 NumPy 배열(array)로 변환, 혹은 그 반대로 하기

(CPU 상의) Torch Tensor와 NumPy 배열은 저장공간을 공유하여 하나를 변경하면 다른 하나도 변경

In [30]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [31]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


NumPy 배열의 값의 변화 확인

In [32]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


NumPy(np) 배열을 변경 시 torch Tensor의 값의 변화 확인

In [33]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA Tensors

`.to` 메소드를 사용하여 Tensor의 device 옮기기

In [35]:
# 이 코드는 CUDA가 사용 가능한 환경에서만 실행 가능
# ``torch.device`` 를 사용하여 tensor를 GPU 안팎으로 이동해보자!
if torch.cuda.is_available():
    device = torch.device("cuda")  # CUDA 장치 객체(device object)로
    y = torch.ones_like(x, device=device)  # GPU 상에 직접적으로 tensor를 생성하거나
    x = x.to(device)  # ``.to("cuda")`` 를 사용
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))  # ``.to`` 는 dtype도 함께 변경함

tensor([1.3610], device='cuda:0')
tensor([1.3610], dtype=torch.float64)
